### ISSUE TITLE
High CPU usage in rules.next

### ISSUE THREAD

**Issue by mcginne** [IBM-Cloud/go-etcd-rules#67]
On our performance carrier we often see the armada-ingress processes go to 600% CPU.

I ran the go pprof tool against it and it shows almost all the CPU is being consumed under:
`github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*etcdV3KeyWatcher).next`

Cumulative top cpu consumers:
```
(pprof) top20 -cum
93.58s of 96.59s total (96.88%)
Dropped 34 nodes (cum <= 0.48s)
Showing top 20 nodes out of 23 (cum >= 1.06s)
      flat  flat%   sum%        cum   cum%
         0     0%     0%     96.55s   100%  runtime.goexit
     8.31s  8.60%  8.60%     96.53s 99.94%  github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*etcdV3KeyWatcher).next
         0     0%  8.60%     96.53s 99.94%  github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*watcher).run
         0     0%  8.60%     96.53s 99.94%  github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*watcher).singleRun
     1.38s  1.43% 10.03%     66.78s 69.14%  runtime.selectgo
    31.18s 32.28% 42.31%     64.50s 66.78%  runtime.selectgoImpl
     4.33s  4.48% 46.80%     14.40s 14.91%  runtime.selunlock
     3.84s  3.98% 50.77%     13.12s 13.58%  runtime.sellock
     3.39s  3.51% 54.28%     11.86s 12.28%  runtime.selectrecv
    10.07s 10.43% 64.71%     10.07s 10.43%  runtime.unlock
     9.29s  9.62% 74.32%      9.29s  9.62%  runtime.lock
     6.37s  6.59% 80.92%      6.37s  6.59%  runtime.selectrecvImpl
     1.24s  1.28% 82.20%      3.73s  3.86%  runtime.typedmemclr
     3.38s  3.50% 85.70%      3.38s  3.50%  runtime.duffzero
     2.16s  2.24% 87.94%      2.17s  2.25%  runtime.newselect
```

Flat top CPU consumers:
```
(pprof) top20
1.61mins of 1.61mins total (99.94%)
Dropped 34 nodes (cum <= 0.01mins)
Showing top 20 nodes out of 23 (cum >= 0.01mins)
      flat  flat%   sum%        cum   cum%
  0.52mins 32.28% 32.28%   1.07mins 66.78%  runtime.selectgoImpl
  0.17mins 10.43% 42.71%   0.17mins 10.43%  runtime.unlock
  0.15mins  9.62% 52.32%   0.15mins  9.62%  runtime.lock
  0.14mins  8.60% 60.93%   1.61mins 99.94%  github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*etcdV3KeyWatcher).next
  0.11mins  6.59% 67.52%   0.11mins  6.59%  runtime.selectrecvImpl
  0.07mins  4.48% 72.01%   0.24mins 14.91%  runtime.selunlock
  0.06mins  3.98% 75.98%   0.22mins 13.58%  runtime.sellock
  0.06mins  3.51% 79.49%   0.20mins 12.28%  runtime.selectrecv
  0.06mins  3.50% 82.99%   0.06mins  3.50%  runtime.duffzero
```
If I dump the goroutines I can see several goroutines in:
```
goroutine 368 [runnable]:
github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*etcdV3KeyWatcher).next(0xc42022eb60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/Armada-Microservices/armada-ingress/src/github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules/etcd.go:175 +0x106
github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*watcher).singleRun(0xc42073c0a0)
	/home/jenkins/workspace/Armada-Microservices/armada-ingress/src/github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules/watcher.go:72 +0x4c
github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*watcher).run(0xc42073c0a0)
	/home/jenkins/workspace/Armada-Microservices/armada-ingress/src/github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules/watcher.go:57 +0x64
created by github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*v3Engine).Run
	/home/jenkins/workspace/Armada-Microservices/armada-ingress/src/github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules/engine.go:384 +0x459
```

Which shows them at this line:

https://github.com/IBM-Bluemix/go-etcd-rules/blob/master/rules/etcd.go#L175

I also see some of them at:
```
goroutine 367 [runnable]:
github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/coreos/etcd/clientv3.(*WatchResponse).Err(0xc420a63d28, 0xc42086c4e0, 0xc420a63d80)
	/home/jenkins/workspace/Armada-Microservices/armada-ingress/src/github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/coreos/etcd/clientv3/watch.go:81 +0xd5
github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*etcdV3KeyWatcher).next(0xc42022eaf0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/Armada-Microservices/armada-ingress/src/github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules/etcd.go:187 +0x1b6
github.ibm.com/alchemy-containers/armada-ingress-microservice/vendor/github.com/IBM-Bluemix/go-etcd-rules/rules.(*watcher).singleRun(0xc42073c050)
```

I will attach the goroutines dump and the profile pdf (which shows the call stacks)
[profile001.pdf](https://github.com/IBM-Bluemix/go-etcd-rules/files/1539507/profile001.pdf)
[ingress_goroutines.txt](https://github.com/IBM-Bluemix/go-etcd-rules/files/1539508/ingress_goroutines.txt)

**Comment by jswarren4** [comment]
Fixed by https://github.com/IBM-Bluemix/go-etcd-rules/pull/68
